[build]
  command = "npm run build"
  publish = "build" # Altere para 'dist' se estiver usando Vite, por exemplo

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
